### ISSUE TITLE
I can't install RobCoG

### ISSUE THREAD

**Issue by UdonDa** [robcog-iai/RobCoG#14]
I can't install RobCoG because I don't know 
> Copy these two plugins to Unreal project's Plugins directory

I'm using Windows10 and UE4 v4.17.2.
Sorry, please tell me how to install RobCoG.

https://github.com/robcog-iai/RobCoG/tree/robosim/Documentation#installation

**Comment by andreihaidu** [comment]
you need to install the two plugins, you can pull them as submodules with:
``` git submodule update --init --recursive ```
