### ISSUE TITLE
Errors while building robosim

### ISSUE THREAD

**Issue by TheRobotStudio** [robcog-iai/RobCoG#18]
Hi, when I launch the RobCoG robosim project in UE4 (4.18) from a terminal, it asks me to rebuild the binaries and the plugins. It seems it succeed to build the plugins, but for the main source it gives me this error : 
```
In file included from /home/cyril/Documents/Unreal_Projects/RobCoG/Source/RobCoG/RosStringSubScriber.cpp:3:
In file included from ../../../Documents/Unreal_Projects/RobCoG/Source/RobCoG/RosStringSubScriber.h:8:
../../../Documents/Unreal_Projects/RobCoG/Source/RobCoG/FROSStringSubScriber.h:14:22: error: variable has incomplete type 'class HELLOWORLD_API'
class HELLOWORLD_API FROSStringSubScriber : public FROSBridgeSubscriber {
```
I can't find where HELLOWORLD_API is defined.
Do you know how to solve this ?

Thanks, kind regards.

**Comment by andreihaidu** [comment]
Hi, the robosim branch, the ros string publisher and subscriber are currently not subscribing, the branch will however be moved to https://github.com/robcog-iai/RobCoG/tree/ex-ros-tf-robosim , currently not documented, but there the examples should compile. Let me know if you run into other issues.

**Comment by TheRobotStudio** [comment]
Ok, I tried to replace HELLOWORLD_API by ROBCOG_API which is the project name. That solves the issue but come up with new errors. I appreciate it's under development so I'll try the examples from ex-ros-tf-robosim.
Thanks!

**Comment by andreihaidu** [comment]
the ex-ros-tf-robosim branch should be a bit more up to date now, I will remove robosim to avoid future issues. Cheers!

**Comment by TheRobotStudio** [comment]
Ok, thanks. I'm not so used to use submodules with git, how do you actually checkout/pull the plugins ?
I tried:
`git submodule update --init --recursive`
which seems to have worked but it still leaves me with empty Plugins directories. Seems like it has done a fetch but no checkout of the specific commits for each submodule.
Cheers!
