### ISSUE TITLE
RobCog couldnt be compiled for Macos

### ISSUE THREAD

**Issue by mohGhazala96** [robcog-iai/RobCoG#259]
After I cloned the repo and install the plugins per the instruction in the README. I get "Missing RobCoG Modules. The following modules are missing or built with a different engine version:
RobCoG
SemLog
SemLogEd
Would you like to rebuild them now?" 

After I click Yes, I get an error when I try to build this project on Macos : " RobCog couldnt be compiled for Macos. Try to build from source"
I also tried with Unreal versions 4.27 and 4.25 with the respective RobCoG branch. I tried to build from source but all the instructions I found support windows https://docs.unrealengine.com/4.26/en-US/ProductionPipelines/DevelopmentSetup/BuildingUnrealEngine/ .  You can check the log file's output here https://pastebin.com/HYPLqj5U.
Please tell me if I missing something or how can I build from source on Mac Os.

**Comment by andreihaidu** [comment]
I never tried building it on Mac OS. Windows in mainly tested together with Linux.
