### ISSUE TITLE
new in unreal robot simulation

### ISSUE THREAD

**Issue by jianghe01** [robcog-iai/RobCoG#29]
hi, I`m new in unreal also robot simulation. Your work is great for me. But I still have many problem in my project.
At first, I drug a urdf model (pr2) into my unreal project and created ros-bridge communication by your plugins. Then I found the pr2 actor in unreal world could not stand on the other static mesh which i used it as scenario.
Secondly I added a camera component with the robot actor. When I tried to move the robot actor by adding force to joints the actor`s location, rotation and the camera component did not move with the actor. When I tried to move the robot actor by set location the robot did not move.
Thirdly the robot`s arms and such components can not hold on itself. When I start play the game, the robot`s arms just hung down.
Can you give me some advice to solve my problem. Thank you very much.

**Comment by andreihaidu** [comment]
the robot simulator is still in a very experimental state. It is not very useful for end users. The project was mainly used for testing the simulation capabilities of game engines. We are still working on improving this, we do not have however an estimate when this will be usable for end users.
